macro(x_link_gdiplus)
	if(NOT OS_WIN)
		message(FATAL_ERROR "Only windows support gdi+.")
	endif()
	list(APPEND X_CURRENT_PACKAGE_LINK_LIBRARYS "gdiplus.lib")
endmacro()

macro(x_link_dl)
	if(OS_WIN)
		message(FATAL_ERROR "Only unix support dl.")
	endif()
	list(APPEND X_CURRENT_PACKAGE_LINK_LIBRARYS "dl")
endmacro()

macro(x_link_pthread)
	if(OS_WIN)
		message(FATAL_ERROR "Only unix support pthread.")
	endif()
	find_library(LIBPTHREAD "pthread")
	list(APPEND X_CURRENT_PACKAGE_LINK_LIBRARYS ${LIBPTHREAD})
endmacro()
