# find _radio_options in _input and then remove it in _input
# if no found _default is returned 
# if more then one found error occused
# example: _token_radio_option(ARGN "AAA|BBB|CC" "BBB" _result)
function(_token_radio_option _input _radio_options _default _output)
	set(_l ${${_input}})
	string(REGEX MATCHALL "[^|]+" _opts "${_radio_options}")
	set(_nhit 0)
	set(_hit)
	foreach(_x ${_l})
		list(FIND _opts "${_x}" _idx)
		if(NOT _idx EQUAL -1)
			math(EXPR _nhit "${_nhit}+1")
			set(_hit "${_x}")
		endif()
	endforeach()
	if(_nhit EQUAL 0)
		set(${_output} ${_default} PARENT_SCOPE)
	elseif(_nhit EQUAL 1)
		set(${_output} ${_hit} PARENT_SCOPE)
		list(REMOVE_ITEM _l "${_hit}")
		set(${_input} ${_l} PARENT_SCOPE)
	else()
		message(FATAL_ERROR "radio option check error!")
	endif()
endfunction()
